# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  host: localhost:3000
  bitext_token: secret
  meaningcloud_token: ea6621706777bb3aa09530e11ab80512
  twitter_dashboard_key: x5o5hcKEnGs7sKYo2kBe3ZwSK
  twitter_dashboard_secret: JP7Gs7sbZxVOSmWH4RSLTY5BGFV6Req96Pr0tyjFFuJiEkQXFg
  twitter_speaker_key: PIBxTpsR5TI8vdLneVgx7cQfl
  twitter_speaker_secret: pavbxg3tBPfnXIG51wgil4sIy4ldCNeek7aBzWJVuhYZq3nnEW
  secret_key_base: 732cc4a46c34ef4cafa3b0da86dcea048aad61b3342568bdba580058e5d21adba82426b183d08a4ca221c57414d00a020bae4e752d5533f61fede0d370b221c0
  sentiment140_email: person@email.com
  collector_size: 10

test:
  host: localhost
  secret_key_base: 3fa33b3dfcae7eb8596fa1c13204d227e899c6645bce1b46c52e6383caaf2d2680b54ece2be1ff29cb5028974144d16e3b96642618bb36e149a509f262949d54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  host: wuxi.cuxibamba.com
  twitter_dashboard_key: <%= ENV["TWITTER_DASHBOARD_KEY"] %>
  twitter_dashboard_secret: <%= ENV["TWITTER_DASHBOARD_SECRET"] %>
  twitter_speaker_key: <%= ENV["TWITTER_SPEAKER_KEY"] %>
  twitter_speaker_secret: <%= ENV["TWITTER_SPEAKER_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  bitext_token: <%= ENV["BITEXT_TOKEN"] %>
  meaningcloud_token: <%= ENV["MEANINGCLOUD_TOKEN"] %>
  sentiment140_email: <%= ENV["SENTIMENT140_EMAIL"] %>
  collector_size: 100

staging:
  host: wuxi-dev.herokuapp.com
  twitter_dashboard_key: <%= ENV["TWITTER_DASHBOARD_KEY"] %>
  twitter_dashboard_secret: <%= ENV["TWITTER_DASHBOARD_SECRET"] %>
  twitter_speaker_key: <%= ENV["TWITTER_SPEAKER_KEY"] %>
  twitter_speaker_secret: <%= ENV["TWITTER_SPEAKER_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
